### ISSUE TITLE
What codec are supported

### ISSUE THREAD

**Issue by Josh65-2201** [ipsk/Holovid#25]
I've gotten this on multiple attempts to download videos

```
[14:02:21 WARN]: org.jcodec.api.UnsupportedFormatException: Codec is not supported
[14:02:21 WARN]:        at Holovid.jar//org.jcodec.api.FrameGrab.detectDecoder(FrameGrab.java:216)
[14:02:21 WARN]:        at Holovid.jar//org.jcodec.api.FrameGrab.createFrameGrab(FrameGrab.java:69)
[14:02:21 WARN]:        at Holovid.jar//me.mattstudios.holovid.download.VideoProcessor.play(VideoProcessor.java:63)
[14:02:21 WARN]:        at Holovid.jar//me.mattstudios.holovid.download.VideoDownloader.saveDataAndPlay(VideoDownloader.java:62)
[14:02:21 WARN]:        at Holovid.jar//me.mattstudios.holovid.download.YouTubeDownloader.download0(YouTubeDownloader.java:68)
[14:02:21 WARN]:        at Holovid.jar//me.mattstudios.holovid.download.VideoDownloader.download(VideoDownloader.java:33)
[14:02:21 WARN]:        at Holovid.jar//me.mattstudios.holovid.Holovid.download(Holovid.java:250)
[14:02:21 WARN]:        at Holovid.jar//me.mattstudios.holovid.command.DownloadCommand.lambda$download$0(DownloadCommand.java:37)
[14:02:21 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[14:02:21 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[14:02:21 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[14:02:21 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[14:02:21 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[14:02:21 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Josh65-2201** [comment]
found it on https://github.com/jcodec/jcodec
